name: docker
on:
  push:
    branches:
    - main

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push appagent
      uses: docker/build-push-action@v2
      with:
        context: ./long-termination
        file: ./long-termination/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository }}/long-termination:stable